# Generated by Django 3.1 on 2022-03-08 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210204_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userFriends', to=settings.AUTH_USER_MODEL),
        ),
    ]
