# Generated by Django 3.1 on 2022-03-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_remove_exerciseinstance_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseinstance',
            old_name='weight',
            new_name='info',
        ),
        migrations.AddField(
            model_name='exercise',
            name='info',
            field=models.CharField(default='', max_length=50),
        ),
    ]
