# Generated by Django 3.1 on 2022-03-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_ingredient_ingredientinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='carbohydrates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='meal',
            name='protein',
            field=models.IntegerField(default=0),
        ),
    ]
