name: GitHub Actions CI
on: 
  push: 
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.8
    defaults:
      run:
        working-directory: ./backend/secfit
    steps:
    # this configures Django application to use attached postgres database that is run on `postgres` host
      - uses: actions/checkout@v1
      - working-directory: ./
        run: apt-get update -qy
      - run: pip install -r requirements.txt
      - run: python manage.py test

  staging:
    runs-on: ubuntu-latest
    container: ruby
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v1
      - run: apt-get update -qy
      - run: apt-get install -y ruby-dev
      - run: gem install dpl
      - run: dpl --provider=heroku --app=tdt4242-ex2-frontend --api-key=${{ secrets.HEROKU_STAGING_API_KEY }}
      - run: dpl --provider=heroku --app=tdt4242-ex2-backend --api-key=${{ secrets.HEROKU_STAGING_API_KEY }}